#**In-Class Practice Session**

###**Downloading the dataset from the Dropbox**

In [ ]:
#Downloading the Dataset from the Dropbox

!wget https://www.dropbox.com/s/kpzd0uzqczklfly/US%20Superstore%20data.xls

###**Importing Required Libraries**

In [ ]:
#Importing Required Libraries

import pandas as pd
import numpy as np
# df = pd.read_excel('US Superstore data.xls')
# df.head(2)

In [ ]:
pip install --upgrade xlrd

## **Practice Session 1**

**Task 1:** Create a dataframe from the following list representing total rainfall in the month of June in Kerala (a State in India) in 9 years.

> lst1 = [350, 500, 600, 700, 600, 500, 600, 300, 550]

**What is the average rainfall in 9 years?**

*Hint: Create a dataframe from the list and calculate mean*

In [ ]:
lst1 = [350, 500, 600, 700, 600, 500, 600, 300, 550]
df1 = pd.DataFrame(lst1, columns=['rainfall'])
df1.mean()

In [ ]:
df1.head()

**Task 2:** Data of another year is now available. Recalculate the mean rainfall for 10 years.

> lst2 = [350, 500, 600, 700, 600, 500, 600, 300, 550, 1400]

In [ ]:
lst2 = [350, 500, 600, 700, 600, 500, 600, 300, 550, 1400]
df2 = pd.DataFrame(lst2)
df2.mean()

**Observation:** Due a very heavy rainfall (1400 mm.) in just one year, the mean is significantly shifted from 522.2 to 610.

**There must another more robust way of calculating the average rainfall.**

**Task 3:** Calculate median for data of 9 years and 10 years separately and compare the results.

In [ ]:
df1.median()

In [ ]:
df2.median()

**Observation:** Median only shifts from 550 to 575 even after addition of an exceptionally high data point.

**Median is more robust to *Outliers* as compared to Mean.**

Note: Outliers are the extremely high or extremely low values in data. You will learn about outliers in detail later.

**Task 4:** Calculate the most common amount of rainfall.

Hint: Calculate the mode separately for 9 years and 10 years of data and compare.

In [ ]:
df1.mode()

In [ ]:
df2.mode()

**Observation:** The most common amount of rainfall is 600 mm irrespective of addition of an outlier.

**Additional Task:** View the distribution of data using a Histogram.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(df1)
plt.show()

In [ ]:
sns.distplot(df2)
plt.show()

In [ ]:
sns.boxplot(df1['rainfall'])

**Observation:** Second plot clearly indicates the presence of an outlier on the extreme right (called Right-skewness).

## **Practice Session 2**

###**Calculate the Measures of Central Tendency - Mean, Median, and Mode for the Quantity column (Use DataFrame Functions)**

In [ ]:
df = pd.read_excel('US Superstore data.xls')
print(df.shape)
df.head(2)

In [ ]:
df['Quantity'].mean().round(2)

In [ ]:
df['Quantity'].median().round(2)

In [ ]:
md = df['Quantity'].mode()
print(md)